# Generated by Django 6.1.1 on 2026-09-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='scenes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
