"use client";

import { useState } from "react";
import { addScene, deleteScene, regenerateScene, updateScene } from "@/lib/api";
import { Scene, Video } from "@/types/video";

interface Props { video: Video; onChange: (video: Video) => void; onRegenerate: () => void; }

export default function ScriptEditor({ video, onChange, onRegenerate }: Props) {
  const [editing, setEditing] = useState<number | null>(null);
  const [draft, setDraft] = useState<Pick<Scene, "narration" | "visual_prompt">>({ narration: "", visual_prompt: "" });
  const [working, setWorking] = useState<number | null>(null);
  const [error, setError] = useState("");
  function startEditing(scene: Scene) { setEditing(scene.scene_number); setDraft({ narration: scene.narration, visual_prompt: scene.visual_prompt }); setError(""); }
  async function saveScene(sceneNumber: number) { try { setWorking(sceneNumber); onChange(await updateScene(video.id, sceneNumber, draft)); setEditing(null); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not save this scene."); } finally { setWorking(null); } }
  async function removeScene(sceneNumber: number) { if (!window.confirm("Delete this scene from the script?")) return; try { setWorking(sceneNumber); onChange(await deleteScene(video.id, sceneNumber)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not delete this scene."); } finally { setWorking(null); } }
  async function regenerate(sceneNumber: number) { try { setWorking(sceneNumber); await regenerateScene(video.id, sceneNumber); onRegenerate(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not regenerate this scene."); } finally { setWorking(null); } }
  async function appendScene() { try { setWorking(-1); onChange(await addScene(video.id)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not add a scene."); } finally { setWorking(null); } }
  return <section className="mt-8 border border-zinc-800 bg-zinc-900 p-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Generated Script</h2><p className="mt-1 text-sm text-zinc-400">Review each scene before generating the video.</p></div><div className="text-right text-sm text-zinc-400"><div>{video.template_settings?.name || "Video"} · {video.template_settings?.aspect_ratio || "9:16"}</div><div className="mt-1">{video.visual_style} · {video.voice}</div></div></div>
    {error && <p className="mt-5 border-l-2 border-red-500 pl-3 text-sm text-red-400">{error}</p>}
    <div className="mt-6 divide-y divide-zinc-800 border-y border-zinc-800">{video.scenes.map((scene) => { const isEditing = editing === scene.scene_number; const isWorking = working === scene.scene_number; return <article key={scene.scene_number} className="py-6 first:pt-5 last:pb-5"><div className="flex items-center justify-between gap-3"><h3 className="font-semibold">Scene {scene.scene_number}</h3>{scene.status === "regenerating" && <span className="text-xs text-purple-400">Regenerating...</span>}</div>{isEditing ? <div className="mt-5 space-y-4"><label className="block text-sm font-medium text-zinc-300">Narration<textarea value={draft.narration} onChange={(e) => setDraft({ ...draft, narration: e.target.value })} rows={4} className="mt-2 w-full resize-y rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-white outline-none focus:border-purple-500" /></label><label className="block text-sm font-medium text-zinc-300">Visual<textarea value={draft.visual_prompt} onChange={(e) => setDraft({ ...draft, visual_prompt: e.target.value })} rows={4} className="mt-2 w-full resize-y rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-white outline-none focus:border-purple-500" /></label><div className="flex gap-3"><button onClick={() => saveScene(scene.scene_number)} disabled={isWorking} className="rounded-lg bg-purple-600 px-4 py-2 text-sm font-medium hover:bg-purple-500 disabled:opacity-50">Save</button><button onClick={() => setEditing(null)} className="rounded-lg border border-zinc-700 px-4 py-2 text-sm hover:border-zinc-500">Cancel</button></div></div> : <><div className="mt-5 grid gap-5 md:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">Narration</p><p className="mt-2 whitespace-pre-line leading-7 text-zinc-200">{scene.narration}</p></div><div><p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">Visual</p><p className="mt-2 whitespace-pre-line leading-7 text-zinc-300">{scene.visual_prompt}</p></div></div><div className="mt-5 flex flex-wrap gap-3"><button onClick={() => regenerate(scene.scene_number)} disabled={isWorking} className="rounded-lg border border-purple-500/60 px-4 py-2 text-sm text-purple-300 hover:bg-purple-500/10 disabled:opacity-50">Regenerate Scene</button><button onClick={() => startEditing(scene)} className="rounded-lg border border-zinc-700 px-4 py-2 text-sm hover:border-zinc-500">Edit</button><button onClick={() => removeScene(scene.scene_number)} disabled={isWorking} className="rounded-lg border border-red-500/40 px-4 py-2 text-sm text-red-300 hover:bg-red-500/10 disabled:opacity-50">Delete Scene</button></div></>}</article>; })}</div>
    <button onClick={appendScene} disabled={working !== null} className="mt-6 rounded-lg border border-zinc-700 px-4 py-2 text-sm font-medium hover:border-purple-500 disabled:opacity-50">Add Scene</button>
  </section>;
}
